- name: Ansible setup
  include_tasks: ansible.yml
- name: apt update && apt upgrade
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 3600
- name: base packages
  apt:
    state: present
    name:
      - chrony
      - git
      - vim
- name: Global python packages
  pip:
    name:
      - awscli
    state: present
# https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html#configure-amazon-time-service-ubuntu
- name: Configure chrony for Amazon Time Sync Service
  lineinfile:
    path: /etc/chrony/chrony.conf
    regexp: "server 169.254.169.123 prefer iburst"
    insertbefore: BOF
    line: "{% if hyperbola_environment != 'production' %}# {% endif %}server 169.254.169.123 prefer iburst"
  notify: restart chrony
- name: Document chrony config for Amazon Time Sync Service
  lineinfile:
    path: /etc/chrony/chrony.conf
    insertbefore: "server 169.254.169.123 prefer iburst"
    line: "# Amazon Time Sync Service: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html"
  notify: restart chrony
- name: Lock root account # http://stackoverflow.com/a/39018859
  user:
    name: root
    state: present
- name: Passwordless sudo --list
  lineinfile:
    dest: /etc/sudoers
    line: "{{ item }}"
    state: present
    validate: "visudo -cf %s"
  with_items:
    - "ALL ALL=(ALL) NOPASSWD: /usr/bin/sudo -l"
    - "ALL ALL=(ALL) NOPASSWD: /usr/bin/sudo --list"
- name: /hyperbola directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /hyperbola
