# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifestream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifestreamitem',
            name='blurb',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lifestreampicture',
            name='picture',
            field=models.ImageField(upload_to='lifestream/photos/%Y/%m/%d/%H-%M/'),
        ),
    ]
