# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import hyperbola.core


class Migration(migrations.Migration):

    dependencies = [("lifestream", "0002_auto_20160710_0402")]

    operations = [
        migrations.AlterField(
            model_name="lifestreamitem",
            name="pub_date",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="lifestreampicture",
            name="picture",
            field=models.ImageField(upload_to=hyperbola.core.MakeUploadTo("lifestream")),
        ),
    ]
