---

python_default_packages:
  - git
  - yum-utils
  - gcc
  - gcc-c++
  - libstdc++-devel
  - libtool
  - mysql-devel
  - postgresql-devel
  - libcurl
  - libcurl-devel
  - curl
  - readline
  - readline-devel
  - bzip2-devel
  - bzip2-libs
  - nss-devel

python_default_packages_centos:
  - openssl

python_default_packages_amzn:
  - openssl-1.0.2k
  - openssl-devel-1.0.2k

# vi:ts=2:sw=2:et:ft=yaml
