---
- hosts: all
  become: true
  become_method: sudo
  become_user: root
  gather_facts: no
  pre_tasks:
  - name: 'install aptitude'
    raw: apt-get -y install aptitude
    tags:
    - skip_ansible_lint
  - name: 'install python2' # http://stackoverflow.com/a/34402816
    raw: apt-get -y install python python-simplejson python-apt python-passlib
    tags:
    - skip_ansible_lint
