---
- name: Include hyperbola app environment
  include_vars:
    file: "{{ hyperbola_environment }}.yml"
    name: app_hyperbola_env
  no_log: True

# deploy user
- name: Create app group
  group:
    name: hyperbola-app
    state: present
- name: Create app user
  user:
    name: hyperbola-app
    state: present
    group: hyperbola-app
    shell: /bin/bash

# install system package dependencies
- name: Install hyperbola build deps
  apt: name={{ item }} state=present
  with_items:
  - make
  - build-essential
  - libssl-dev
  - libffi-dev
  - rsync
  - python3
  - python3-dev
  - python3-pip
  - libmysqlclient-dev

# install python app
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - /hyperbola/app
- name: Initialize the deploy root and gather facts
  deploy_helper:
    path: /hyperbola/app
- name: Create new release path
  file:
    path: "{{ deploy_helper.new_release_path }}"
    state: directory
- name: Add an unfinished file, to allow cleanup on successful finalize
  file:
    path: "{{ deploy_helper.new_release_path }}/{{ deploy_helper.unfinished_filename }}"
    state: touch
- name: Fetch git tag
  unarchive:
    src: "{{ app_release_download_url }}"
    dest: "{{ deploy_helper.new_release_path }}"
    remote_src: True
- name: Find unpacked archive name
  find:
    paths: "{{ deploy_helper.new_release_path }}"
    patterns: "*hyperbola*"
    file_type: directory
  register: app_release
- name: Set artifact source root
  set_fact:
    app_source_root: "{{['path'] | map('extract',  app_release.files | first) | list | first }}"
- name: Create app virtualenv
  command: "python3 -m venv {{ deploy_helper.new_release_path }}/venv"
  args:
    creates: "{{ deploy_helper.new_release_path }}/venv/bin/python"
- name: Update pip infra
  pip:
    state: latest
    executable: "{{ deploy_helper.new_release_path }}/venv/bin/pip"
    name: "{{ item }}"
  with_items:
    - virtualenv
    - pip
    - pipenv
    - wheel
    - setuptools
  tags:
    - skip_ansible_lint
- name: Install app dependencies
  command: "{{ deploy_helper.new_release_path }}/venv/bin/pipenv install"
  args:
    chdir: "{{ app_source_root }}"
    creates: "{{ deploy_helper.new_release_path }}/venv/**/*django*"
  environment:
    VIRTUAL_ENV: "{{ deploy_helper.new_release_path }}/venv"
- name: Install app
  command: "{{ deploy_helper.new_release_path }}/venv/bin/python setup.py install"
  args:
    chdir: "{{ app_source_root }}"
    creates: "{{ deploy_helper.new_release_path }}/venv/**/*hyperbola*"
  environment:
    PBR_VERSION: "{{ app_version }}"
    SKIP_GIT_SDIST: 1
    SKIP_GENERATE_AUTHORS: 1
    SKIP_WRITE_GIT_CHANGELOG: 1
- name: copy source artifacts to deploy root
  synchronize:
    src: "{{ item }}"
    dest: "{{ deploy_helper.new_release_path }}"
  with_items:
    - "{{ app_source_root }}/dist"
    - "{{ app_source_root }}/document-root"
    - "{{ app_source_root }}/manage.py"
  delegate_to: "{{ inventory_hostname }}"
- name: Set artifact root
  set_fact:
    app_artifact_root: "{{ deploy_helper.new_release_path }}"
- name: Generate settings.SECRET_KEY
  command: "{{ deploy_helper.new_release_path }}/venv/bin/python -c 'import django.core.management.utils; print(django.core.management.utils.get_random_secret_key())'"
  register: app_django_secret_key
  no_log: True
  tags:
    - skip_ansible_lint
- name: Install 12factor environment
  template:
    src: "dotenv.j2"
    dest: "{{ deploy_helper.new_release_path }}/.env"
    mode: 0444
- name: manage.py collectstatic
  command: "{{ deploy_helper.new_release_path }}/venv/bin/python {{ deploy_helper.new_release_path }}/manage.py collectstatic --no-input"
  args:
    creates: "{{ deploy_helper.new_release_path }}/document-root/static/staticfiles.json"
- name: Install gunicorn config
  template:
    src: "gunicorn.py.j2"
    dest: "{{ deploy_helper.new_release_path }}/gunicorn.py"
    mode: a=r
- name: Set owner of deployment to hyperbola-app:hyperbola-app
  file:
    dest: "{{ deploy_helper.new_release_path }}"
    owner: hyperbola-app
    group: hyperbola-app
    mode: a=rX
    recurse: true
- name: Finalize the deploy, removing the unfinished file and switching the symlink
  deploy_helper:
    path: /hyperbola/app
    release: "{{ deploy_helper.new_release }}"
    state: finalize
  notify: restart app

# services
- name: Install systemd units
  copy:
    src: "{{ item }}"
    dest: /etc/systemd/system
    mode: 0444
  with_items:
    - hyperbola-app@.service
    - hyperbola-app-backup@.service
    - hyperbola-app-backup@.timer
  notify: reload systemd units
- name: Enable app instantiated units
  systemd:
    name: "{{ item.unit }}"
    state: "{{ item.state }}"
    enabled: "{{ item.enabled }}"
    daemon_reload: true
  with_items:
    - unit: "hyperbola-app@{{ hyperbola_environment }}.service"
      enabled: true
      state: "{% if hyperbola_environment == 'production' %}stopped{% else %}started{% endif %}"
    - unit: "hyperbola-app-backup@{{ hyperbola_environment }}.service"
      enabled: false
      state: stopped
    - unit: "hyperbola-app-backup@{{ hyperbola_environment }}.timer"
      enabled: true
      state: stopped
