---
- name: Environment-specific secrets
  include_vars:
    file: "{{ hyperbola_environment }}.yml"
    name: app_secrets
  no_log: True
- name: Create app deploy group
  group:
    name: hyperbola-app
    state: present
- name: Create app deploy user
  user:
    name: hyperbola-app
    state: present
    group: hyperbola-app
    shell: /bin/bash
- name: Build dependencies
  include_tasks: build-setup.yml
- name: Add deadsnakes ppa # https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa
  apt_repository: repo='ppa:deadsnakes/ppa'
- name: Install python
  apt:
    state: latest
    name:
      - "{{ app_python }}"
      - "{{ app_python }}-dev"
      - "{{ app_python }}-venv"
  tags:
    - skip_ansible_lint
- name: Deploy app
  include_tasks: app-deploy.yml
- name: Uninstall build dependencies
  include_tasks: build-cleanup.yml
- name: Install systemd units
  include_tasks: services.yml
