# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blurb',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
