# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='photo',
            field=models.ImageField(upload_to='about/photo/%Y/%m/%d/%H-%M/'),
        ),
        migrations.AlterField(
            model_name='contacttype',
            name='type',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='emailcontact',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emailcontact',
            name='value',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='imcontact',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='imcontact',
            name='value',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='phonecontact',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume',
            field=models.FileField(upload_to='resume/%Y/%m/%d/%H-%M/lopopolo.pdf'),
        ),
        migrations.AlterField(
            model_name='webcontact',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
