#!/usr/bin/env bash

PATH="/hyperbola/tools/venv/bin:$PATH"
export PATH

echo "Begin renewal attempt at: $(date)"

sg www-data "/hyperbola/tools/dehydrated/dehydrated --cron --config /hyperbola/tools/tls/wiki.hyperbo.la/config --challenge dns-01 --hook /hyperbola/tools/dehydrated/hooks/cloudflare/hook.py"

echo "Exit code from dehydrated: $?"

umask 0037
chmod -R g+rX "/hyperbola/tls/wiki.hyperbo.la/certs"
