galaxy_info:
  author: Ryan Lopopolo <rjl@hyperbo.la>
  description: Install hyperbo.la nginx, django, and asset configuration.
  license: MIT
  min_ansible_version: 2.7
  platforms:
    - name: Ubuntu
      versions:
        - 18.04
dependencies:
  - role: hyperbola-base
  - role: hyperbola-nginx
    nginx_vhosts:
      - domain: "{{ app_nginx_domain }}"
        index: "01"
        ssl_enabled: true
        template: roles/hyperbola-app/templates/hyperbo.la.conf.j2
