---
dependencies:
- role: hyperbola-base
- role: hyperbola-nginx
  nginx_vhosts:
  - domain: "{{ app_nginx_domain }}"
    index: "01"
    ssl_enabled: true
    template: roles/hyperbola-app/templates/hyperbo.la.conf.j2
- name: Python from source
  role: torian.python
  vars:
    python_version: 3.6.5
    python_bin: /usr/local/bin/python3.6
    python_setuptools_bin: "" # ignored
  when: false
