---
- hosts: app
  become: true
  become_method: sudo
  become_user: root
  roles:
  - role: hyperbola-app
    ssl_enabled: "{{ hyperbola_environment != 'local' }}"
  - role: DavidWittman.redis
    redis_bind: 0.0.0.0
    redis_version: 3.2.9
    when: hyperbola_environment == 'local'
