- hosts: app
  become: true
  become_method: sudo
  become_user: root
  roles:
    - role: hyperbola-app
      app_python: python3.7
      app_node: node_10.x # https://github.com/nodesource/distributions
