---
- hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:
  - name: Update apt cache
    apt:
      update_cache: true
      cache_valid_time: 600
  - name: Install ansible dependencies
    apt:
      name: "{{ item }}"
      state: present
    with_items:
    - python3-apt
    - python3-passlib
    - python3-pip
    - python3-simplejson
    - python3-venv
  # required for some playbooks: https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user
  - name: Install filesystem acls
    apt:
      name: acl
      state: present
