---
- hosts: wiki
  become: true
  become_method: sudo
  become_user: root
  vars_files:
    - vars/cloudflare.yml
  roles:
  - role: hyperbola_base
  - role: ruby
  - role: nginx
    nginx_vhosts:
    - domain: "{{ wiki_nginx_domain }}"
      index: "02"
      hsts: "{{ hyperbola_environment != 'localhost' }}"
      ssl_enabled: true
      template: roles/wiki/templates/02-wiki.hyperbo.la.conf.j2
  - role: tls
    tls_domain: "{{ wiki_nginx_domain }}"
    tls_cloudflare_email: rjl@hyperbo.la
    tls_cloudflare_api_key: "{{ cloudflare_api_key }}"
  - role: wiki
