---
- hosts: wiki
  become: true
  become_method: sudo
  become_user: root
  vars_files:
    - vars/cloudflare.yml
  roles:
  - role: hyperbola-wiki
    ssl_enabled: "{{ hyperbola_environment != 'localhost' }}"
