---
- name: apt update && apt upgrade
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 3600
- name: base packages
  apt: name={{ item }} state=present
  with_items:
  - git
  - vim
