---

- name: Install packages (RedHat)
  yum:
    state: present
    name: "{{item}}"
  with_items: "{{python_default_packages}}"

- name: Install packages (CentOS)
  yum:
    state: present
    name: "{{item}}"
  with_items: "{{python_default_packages_centos|default([])}}"
  when: ansible_distribution == "CentOS"

- name: Install packages (Amazon Linux)
  yum:
    state: present
    name: "{{item}}"
  with_items: "{{python_default_packages_amzn|default([])}}"
  when: ansible_distribution == "Amazon"

- name: Install additional dev packages
  yum:
    state: present
    name: "{{item}}"
  with_items: "{{python_dev_packages}}"

# vi:ts=2:sw=2:et:ft=yaml
